version: "2"
services:
  logstash:
    container_name: "logstash"
    image: logstash
    volumes:
      - ./sample.conf:/opt/logstash/sample.conf
      - /etc/localtime:/etc/localtime:ro
    command: "-f /opt/logstash/sample.conf"
    external_links:
      - elasticsearch
    network_mode: "bridge"
    ports:
      - "5000:5000"

